//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class MenuIngredient
    {
        public int menu_id { get; set; }
        public int ingredient_id { get; set; }
        public decimal weight { get; set; }
    
        public virtual Ingredient Ingredient { get; set; }
        public virtual Menu Menu { get; set; }
    }
}
